### ISSUE TITLE
fix CI

### ISSUE THREAD

**Issue by dcherian** [NCAR/pop-tools#119]
CircleCI is failing and it's not clear to me what it's checking given that we have Github Actions and RTD builds running.

I think we can also delete the `linting` workflow now that `pre-commit.ci` is activated.

@andersy005 does this sound right to you?

**Comment by andersy005** [comment]
> CircleCI is failing and it's not clear to me what it's checking given that we have Github Actions and RTD builds running.

The CircleCI issue should be fixed now (it was due to an old webhook that didn't get uninstalled when we disable CircleCI)

> I think we can also delete the linting workflow now that pre-commit.ci is activated.

#120 fixes this.

**Comment by dcherian** [comment]
Wonderful. Thanks  Anderson!
