### ISSUE TITLE
There might a mistake in example “Using xgcm with POP output”

### ISSUE THREAD

**Issue by jwy-wbe** [NCAR/pop-tools#137]
Thers is a line in example:"GX_x, GY_x = gradh_xr(ds.TEMP, ds.DXT, ds.DYU)  # xarray version", I think the second parameter of function ”gradh_xr“ should be “ds.DXU”

**Comment by ALDepp** [comment]
DXT and DYU are inconsistent, thanks, that's a good catch! 
It should be DYU and DXU (as it is done in gradh_xgcm()). These are the distances between the T points (equivalent to the cell size in Y and X around the U points), have a look at the schematic here: https://pop-tools.readthedocs.io/en/latest/examples/CloseHeatBudget_POP2.html
