### ISSUE TITLE
How I can apply this tool onto MOM outputs?

### ISSUE THREAD

**Issue by ars599** [NCAR/pop-tools#156]
It is a fantastic tool, however, how I can apply to MOM outputs?

I have read in data and try to calculate the heat budget from the examples:

The python
=====================
gridxgcm, dsxgcm = pop_tools.to_xgcm_grid_dataset(
    ds,
    periodic=False,
    metrics=metrics,
    boundary={"X": "extend", "Y": "extend", "Z": "extend"},
)

ds is the output file from MOM

The error message:
====================
/g/data4/p66/ars599/pop-tools/pop_tools/xgcm_util.py in to_xgcm_grid_dataset(ds, metrics, **kwargs)
    226             """to_xgcm_grid_dataset() function requires the `xgcm` package. \nYou can install it via PyPI or Conda"""
    227         )
--> 228     ds_new = relabel_pop_dims(ds)
    229     if metrics == 'detect':
    230         metrics = get_metrics(ds_new)

/g/data4/p66/ars599/pop-tools/pop_tools/xgcm_util.py in relabel_pop_dims(ds)
     88     """
     89     ds_new = _label_coord_grid_locs(ds)
---> 90     ds_new = _add_pop_dims_to_dataset(ds_new)
     91     for vname in ds_new.variables:
     92         if 'grid_loc' in ds_new[vname].attrs:

/g/data4/p66/ars599/pop-tools/pop_tools/xgcm_util.py in _add_pop_dims_to_dataset(ds)
     12     ds_new = ds.copy()
     13     ds_new['nlon_u'] = xr.Variable(
---> 14         ('nlon_u'), np.arange(len(ds.nlon)) + 1, {'axis': 'X', 'c_grid_axis_shift': 0.5}
     15     )
     16     ds_new['nlat_u'] = xr.Variable(

/g/data/hh5/public/apps/miniconda3/envs/analysis3-22.01/lib/python3.9/site-packages/xarray/core/common.py in __getattr__(self, name)
    237                 with suppress(KeyError):
    238                     return source[name]
--> 239         raise AttributeError(
    240             f"{type(self).__name__!r} object has no attribute {name!r}"
    241         )

AttributeError: 'Dataset' object has no attribute 'nlon'

I understand the nlon in MOM is xt_ocean, and we have something such al yt_ocean, st_ocean, DXT... and now  I'am playing POP scrits. I guess I eighter can replace the xt_ocean to nlon and others, or maybe I can just change the source code.

Is there any documentarians to follow? Many thanks!!!

Regards,

Arnold

**Comment by ALDepp** [comment]
Hi @ars599, this package is written to deal with POP output (which is on a B-grid) and make it compatible with xgcm, not MOM (which is on Arakawa C-grid). Feel free to look through the code and adapt the steps for MOM as needed, or alternatively google "MOM xgcm".
