### ISSUE TITLE
Add `pop2xgcm_grid` method 

### ISSUE THREAD

**Issue by andersy005** [NCAR/pop-tools#17]
It might be nice then to add a utility here that converts raw POP output to an xGCM object, or xGCM compatible object, as we discussed before. Ryan Abernathy added a code snippet for this in https://github.com/NCAR/pop-tools/pull/12, and it shows that it's not straight forward to a new user.

_Originally posted by @bradyrx in https://github.com/NCAR/pop-tools/issues/16#issuecomment-527612701_

**Comment by bradyrx** [comment]
From @rabernat, here's a gist of converting raw POP over to xgcm compatible output.

Several people have used xgcm successfully with POP. It does require some modifications to the datasets however. Here is a gist which shows how that works:

    https://gist.github.com/rabernat/933bc785c99828352f343e48d0da6e22

**Comment by andersy005** [comment]
Should we have a `xgcm2pop_grid` method that would be used to convert back to raw POP after xgcm's computation or is it the case that users are okay with xgcm's output?

**Comment by bradyrx** [comment]
I'm not sure that makes sense here. I think `xgcm` is an endpoint that does final calculations and outputs a DataArray/Dataset as its final product. So it should be managable at that point. But this would be something that would be more clear once some examples are put together for `pop2xgcm_grid`.

**Comment by andersy005** [comment]
Sounds good
