### ISSUE TITLE
Test data for Continuous Integration

### ISSUE THREAD

**Issue by andersy005** [NCAR/pop-tools#18]
Now that `ftp://ftp.cgd.ucar.edu/archive/aletheia-data` is up and running, I was wondering if we could establish a shortlist of sample datasets that could be used for pop-tools testing. 

@bradyrx, @matt-long if you could produce some sample data and put it on GLADE, I can upload the data to the FTP server.

**Comment by bradyrx** [comment]
This will be helpful for https://github.com/NCAR/pop-tools/pull/12. I'll put together some lat-lon-depth subset of output to use for testing on the budget computation. I'll follow up in the PR thread on this.
