### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by yuyangyang0709** [NCAR/pop-tools#22]
The error is 
LookupError: setuptools-scm was unable to detect version for '/home/export/online1/cesm04/yuyy/pop-tools-master'.
Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

How can I install it correctly? Please help me, thank you.

**Comment by andersy005** [comment]
@yuyangyang0709, did you figure it out?

If not, have you tried

```bash
pip install git+https://github.com/NCAR/pop-tools.git
```

**Comment by yuyangyang0709** [comment]
Thank you for your reply. The problem has been solved.

**Comment by yuyangyang0709** [comment]
Thank you for your reply. The problem has been solved.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Anderson Banihirwe"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月10日(星期四) 晚上10:11
收件人:&nbsp;"NCAR/pop-tools"<pop-tools@noreply.github.com&gt;;
抄送:&nbsp;"弱视群体、"<123636672@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NCAR/pop-tools] Installation failure (#22)




@yuyangyang0709, did you figure it out?
 
If not, have you tried
 pip install git+https://github.com/NCAR/pop-tools.git
