### ISSUE TITLE
import pop_tools fails on CGD machines / issue with subversion export call

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/pop-tools#24]
This is actually two bugs for the price of one... if you try to import `pop_tools` on a CGD machine (like `andre`), you get an SVN error:

```
>>> import pop_tools
svn: invalid option: --trust-server-cert-failures=unknown-ca
Type 'svn help' for usage.
None
None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/project/oce/mlevy/miniconda3/envs/pop_tools_issue/lib/python3.7/site-packages/pop_tools/__init__.py", line 6, in <module>
    from .config import grid_defs
  File "/project/oce/mlevy/miniconda3/envs/pop_tools_issue/lib/python3.7/site-packages/pop_tools/config.py", line 88, in <module>
    ensure_inputdata()
  File "/project/oce/mlevy/miniconda3/envs/pop_tools_issue/lib/python3.7/site-packages/pop_tools/config.py", line 84, in ensure_inputdata
    svn_export(repo_path, val)
  File "/project/oce/mlevy/miniconda3/envs/pop_tools_issue/lib/python3.7/site-packages/pop_tools/config.py", line 64, in svn_export
    raise Exception('svn error')
Exception: svn error
```

I don't know what the `--trust-server-cert-failures=unknown-ca` used to do / is trying to do, but version 1.8.19 (on CGD machines) and version 1.7.14 (on casper) both throw errors saying it's invalid.

It's kind of a red herring, though -- the real issue is that [config.py#L12](https://github.com/NCAR/pop-tools/blob/master/pop_tools/config.py#L12) hard-codes `/glade/p/cesmdata/cseg/inputdata` as the root for `inputdata/`... if it doesn't exist, the fallback is `~/scratch/inputdata/` which is then populated by `svn export`.

The good news is that this provides an easy work around for CGD machines:

```
$ ln -s /fs/cgd/inputdata ~/scratch
```

Will provide a `scratch/inputdata/` directory that does not require any additional `svn export` calls... however, I think a good long-term fix would be to assume `$CESMDATAROOT` exists, and set 

```
inputdata_local = os.environ['CESMDATAROOT'] + '/inputdata'
```
Then we just need to ask Mark to define it similarly to how it is done on the CISL machines (and in the meantime individual users can set it themselves).

****

Cliff notes:

1. `--trust-server-cert-failures=unknown-ca` is not a valid subversion option, so [config.py#L54](https://github.com/NCAR/pop-tools/blob/master/pop_tools/config.py#L54) needs to be fixed
1. `inputdata_local` is hard-coded to point to a glade directory, so [config.py#L12](https://github.com/NCAR/pop-tools/blob/master/pop_tools/config.py#L12) also needs to be fixed

**Comment by andersy005** [comment]
@mnlevy1981, #23 addresses this issue, and uses the `$CESMDATAROOT` approach you suggested. When you get a chance, please give it a try and let me know how it goes.

**Comment by andersy005** [comment]
I can confirm that this issue appears to be fixed. I tested this by 

- Setting the `$CESMDATAROOT` variable

```bash
export CESMDATAROOT=/fs/cgd/inputdata
```

- Using the master branch of pop-tools (make sure you've installed `pooch >=v0.7.0`)

**Comment by mnlevy1981** [comment]
Updating `pooch` to 0.7 (required `pip` instead of `conda`) and setting `CESMDATAROOT=/fs/cgd/csm/inputdata`, I was able to import pop tools. The import seemed to take several seconds, though the was no additional output to the terminal:

```
>>> import pop_tools
>>>
```

If `pooch` wanted to download files, would there be an indication of that in `stdout`?

**Comment by andersy005** [comment]
> If pooch wanted to download files, would there be an indication of that in stdout?

Yes. Try running the following:

```python
from pop_tools import DATASETS   
path = DATASETS.fetch('tend_zint_100m_Fe.nc') 
```
