### ISSUE TITLE
non-default tol value not propagated through fill call tree

### ISSUE THREAD

**Issue by klindsay28** [NCAR/pop-tools#49]
The call to `lateral_fill_np_array` in `lateral_fill` does not pass `tol`.
As a consequence, if a user passes a non-default `tol` value to `lateral_fill`,
the user-specified value is not getting propagated to `lateral_fill_np_array`.

**Comment by mnlevy1981** [comment]
This was fixed in #57 but I forgot to link the issue to the PR
