### ISSUE TITLE
Refactor questions for `grid.py`

### ISSUE THREAD

**Issue by bradyrx** [NCAR/pop-tools#55]
I noticed in `get_grid` that `_compute_TLAT_TLONG` is called, but it returns nothing and asserts nothing. I.e., it doesn't do any error throwing, warning, or return anything. It seems like a pointless call, unless I'm missing something.

https://github.com/NCAR/pop-tools/blob/903a22689c7d524de3a8ff40192aba5e985a666b/pop_tools/grid.py#L88

Also, can the commented out lines for `DXT`, `DYT`, etc. be removed from `get_grid`?

**Comment by andersy005** [comment]
>. but it returns nothing and asserts nothing. I.e., it doesn't do any error throwing, warning, or return anything.

`_compute_TLAT_TLONG(ULAT, ULONG, TLAT, TLONG, nlat, nlon)` doesn't return anything because it is using the **pass-by-reference model**. As a result, TLAT, and TLONG are modified inside `_compute_TLAT_TLONG`:

```python
In [26]: HTN = grid_file_data[2, :, :].astype(np.float)

In [27]: HTE = grid_file_data[3, :, :].astype(np.float)

In [28]: TLAT = np.empty((nlat, nlon), dtype=np.float)

In [29]: TLONG = np.empty((nlat, nlon), dtype=np.float)

In [30]: TLAT
Out[30]:
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [31]: TLONG
Out[31]:
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]: _compute_TLAT_TLONG(ULAT, ULONG, TLAT, TLONG, nlat, nlon)

In [33]: TLAT
Out[33]:
array([[-1.38265895, -1.38265895, -1.38265895, ..., -1.38265895,
        -1.38265895, -1.38265895],
       [-1.37333512, -1.37333512, -1.37333512, ..., -1.37333512,
        -1.37333512, -1.37333512],
       [-1.36401129, -1.36401129, -1.36401129, ..., -1.36401129,
        -1.36401129, -1.36401129],
       ...,
       [ 1.24425076,  1.24431648,  1.2444478 , ...,  1.2444478 ,
         1.24431648,  1.24425076],
       [ 1.25201619,  1.25207858,  1.25220327, ...,  1.25220327,
         1.25207858,  1.25201619],
       [ 1.25988295,  1.25994153,  1.26005859, ...,  1.26005859,
         1.25994153,  1.25988295]])

In [34]: TLONG
Out[34]:
array([[-0.68831407, -0.66867911, -0.64904416, ..., -0.74721893,
        -0.72758398, -0.70794902],
       [-0.68831407, -0.66867911, -0.64904416, ..., -0.74721893,
        -0.72758398, -0.70794902],
       [-0.68831407, -0.66867911, -0.64904416, ..., -0.74721893,
        -0.72758398, -0.70794902],
       ...,
       [-0.69374515, -0.68497539, -0.67621432, ..., -0.72004877,
        -0.7112877 , -0.70251786],
       [-0.69403725, -0.68585175, -0.67767514, ..., -0.71858795,
        -0.71041134, -0.70222577],
       [-0.69435291, -0.68679875, -0.67925361, ..., -0.71700948,
        -0.70946434, -0.70191012]])
```

**Comment by bradyrx** [comment]
> > . but it returns nothing and asserts nothing. I.e., it doesn't do any error throwing, warning, or return anything.
> 
> `_compute_TLAT_TLONG(ULAT, ULONG, TLAT, TLONG, nlat, nlon)` doesn't return anything because it is using the **pass-by-reference model**. As a result, TLAT, and TLONG are modified inside `_compute_TLAT_TLONG`:
> 
> ```python
> In [26]: HTN = grid_file_data[2, :, :].astype(np.float)
> 
> In [27]: HTE = grid_file_data[3, :, :].astype(np.float)
> 
> In [28]: TLAT = np.empty((nlat, nlon), dtype=np.float)
> 
> In [29]: TLONG = np.empty((nlat, nlon), dtype=np.float)
> 
> In [30]: TLAT
> Out[30]:
> array([[0., 0., 0., ..., 0., 0., 0.],
>        [0., 0., 0., ..., 0., 0., 0.],
>        [0., 0., 0., ..., 0., 0., 0.],
>        ...,
>        [0., 0., 0., ..., 0., 0., 0.],
>        [0., 0., 0., ..., 0., 0., 0.],
>        [0., 0., 0., ..., 0., 0., 0.]])
> 
> In [31]: TLONG
> Out[31]:
> array([[0., 0., 0., ..., 0., 0., 0.],
>        [0., 0., 0., ..., 0., 0., 0.],
>        [0., 0., 0., ..., 0., 0., 0.],
>        ...,
>        [0., 0., 0., ..., 0., 0., 0.],
>        [0., 0., 0., ..., 0., 0., 0.],
>        [0., 0., 0., ..., 0., 0., 0.]])
> 
> In [32]: _compute_TLAT_TLONG(ULAT, ULONG, TLAT, TLONG, nlat, nlon)
> 
> In [33]: TLAT
> Out[33]:
> array([[-1.38265895, -1.38265895, -1.38265895, ..., -1.38265895,
>         -1.38265895, -1.38265895],
>        [-1.37333512, -1.37333512, -1.37333512, ..., -1.37333512,
>         -1.37333512, -1.37333512],
>        [-1.36401129, -1.36401129, -1.36401129, ..., -1.36401129,
>         -1.36401129, -1.36401129],
>        ...,
>        [ 1.24425076,  1.24431648,  1.2444478 , ...,  1.2444478 ,
>          1.24431648,  1.24425076],
>        [ 1.25201619,  1.25207858,  1.25220327, ...,  1.25220327,
>          1.25207858,  1.25201619],
>        [ 1.25988295,  1.25994153,  1.26005859, ...,  1.26005859,
>          1.25994153,  1.25988295]])
> 
> In [34]: TLONG
> Out[34]:
> array([[-0.68831407, -0.66867911, -0.64904416, ..., -0.74721893,
>         -0.72758398, -0.70794902],
>        [-0.68831407, -0.66867911, -0.64904416, ..., -0.74721893,
>         -0.72758398, -0.70794902],
>        [-0.68831407, -0.66867911, -0.64904416, ..., -0.74721893,
>         -0.72758398, -0.70794902],
>        ...,
>        [-0.69374515, -0.68497539, -0.67621432, ..., -0.72004877,
>         -0.7112877 , -0.70251786],
>        [-0.69403725, -0.68585175, -0.67767514, ..., -0.71858795,
>         -0.71041134, -0.70222577],
>        [-0.69435291, -0.68679875, -0.67925361, ..., -0.71700948,
>         -0.70946434, -0.70191012]])
> ```

Got it, I didn't realize this was the case in python. Maybe I just have avoided writing a function this way. I figured that references within the function were private, i.e. modifications to `TLAT` and `TLONG` did not modify the global variable. But I guess this is the reason you're not supposed to have defaults be things like empty lists and dictionaries?
