### ISSUE TITLE
dRHOdT from pop-tool.eos() is derivative of rho with respect to potential or in-situ temperature?

### ISSUE THREAD

**Issue by DapengLi17** [NCAR/pop-tools#69]
Hi Sir/Lady:
    I am analyzing CESM POP outputs and using pop-tools.eos() to compute dRHOdT. I read the doc that dRHOdT is the derivative of rho with respect to temperature. Is dRHOdT the derivative of rho with respect to potential or in-situ temperature? There seems to be a typo in the attribute (unit) of dRHOdS in line 108 of eos.py. I think the unit should be kg/m^3/psu instead of kg/m^3/degC.  
     Any replies are highly appreciated! 
Regards!
Dapeng

**Comment by andersy005** [comment]
Hi @DapengLi17, I'm moving this issue to the discussions page since the discussions page is suitable for Q&A.
